name: ERC4626
plugins:
  - name: vyper
  - name: hardhat
  - name: alchemy
  - name: etherscan

# if you installed hardhat for the first time
# cd into your ERC4626 
# npm install --save-dev hardhat

ethereum:
  default_network: mainnet-fork

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy