services:
  app:
    build: ghcr.io/apeacademy/silverback_yield:latest
    env_file: .env
    environment:
      - DATABASE_URL=sqlite:////data/silverback_yield.db
    command: run
    restart: unless-stopped

